### ISSUE TITLE
Is this a completely separate project to mesos/chronos?

### ISSUE THREAD

**Issue by jwg4** [aol/chronos#3]
You link to the AirBNB project which uses mesos at the end of the README. It looks like a completely different project with a coincident name, is this right? If this is the case I think you should make it clear as it's a little confusing.

**Comment by sinemetu1** [comment]
It's a completely different project. aol/chronos doesn't run on or require mesos.

However I did think that it would be appropriate to link to other projects that have worked on similar problems.

I've seen a few comments about the names being confusing. I guess I didn't realize that people would think that this project is just a ui built on top of AirBnB's chronos.

**Comment by jwg4** [comment]
Thanks! I thought exactly that - this looked like a very reasonable dependency to have, and then when I googled 'chronos' I started to think that I had to be using mesos.
